-- Create scores table
create table scores (
  id bigint generated by default as identity primary key,
  wallet_address text not null,
  score integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  metadata jsonb
);

-- Enable Row Level Security (RLS)
alter table scores enable row level security;

-- Create policy to allow public read access
create policy "Public scores are viewable by everyone."
  on scores for select
  using ( true );

-- Create policy to allow authenticated inserts (or public if using API route with service key)
-- For this implementation, we'll assume the API route handles insertion with the service role key,
-- so we don't strictly need an insert policy for anon users if we block direct client writes.
-- However, if we want to allow client-side writes (not recommended for anti-cheat), we'd add one.
-- We will stick to the API route approach.
